spring.application.name=biblioteca

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.mxxzidfwkocovrhcjhcj
spring.datasource.password=proyectoUTP
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desactivar cache de plantillas para desarrollo inmediato
spring.thymeleaf.cache=false